#!/bin/bash
set -a
source ~/Bureau/datastax/workshop-spring-reactive/.env
set +a
~/Bureau/datastax/workshop-spring-reactive/tools/cqlsh-astra/bin/cqlsh -u token -p ${ASTRA_DB_ADMIN_TOKEN} -b /home/ismael/.astra/scb_${ASTRA_DB_ID}_${ASTRA_DB_REGION}.zip
